// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDHDaPUsESddduduWjg3Pm9XEx4TBQzNk',
    appId: '1:263195764183:web:215115e758a420ec381792',
    messagingSenderId: '263195764183',
    projectId: 'first-app-ec476',
    authDomain: 'first-app-ec476.firebaseapp.com',
    databaseURL: 'https://first-app-ec476-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-ec476.firebasestorage.app',
    measurementId: 'G-TMBNECJKKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3osuQtxyEkfkPZEV6C6zoYkcae09Zdl0',
    appId: '1:263195764183:android:f3efb841edc1ba39381792',
    messagingSenderId: '263195764183',
    projectId: 'first-app-ec476',
    databaseURL: 'https://first-app-ec476-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-ec476.firebasestorage.app',
  );
}
