// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDHDaPUsESddduduWjg3Pm9XEx4TBQzNk',
    appId: '1:263195764183:web:215115e758a420ec381792',
    messagingSenderId: '263195764183',
    projectId: 'first-app-ec476',
    authDomain: 'first-app-ec476.firebaseapp.com',
    storageBucket: 'first-app-ec476.firebasestorage.app',
    measurementId: 'G-TMBNECJKKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3osuQtxyEkfkPZEV6C6zoYkcae09Zdl0',
    appId: '1:263195764183:android:712d4944d7e8b4c7381792',
    messagingSenderId: '263195764183',
    projectId: 'first-app-ec476',
    storageBucket: 'first-app-ec476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFtTfXw8Mh-FU9IMiZiG5MlVgxfYbWX50',
    appId: '1:263195764183:ios:805c7236d9bb663d381792',
    messagingSenderId: '263195764183',
    projectId: 'first-app-ec476',
    storageBucket: 'first-app-ec476.firebasestorage.app',
    iosBundleId: 'com.example.pilem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFtTfXw8Mh-FU9IMiZiG5MlVgxfYbWX50',
    appId: '1:263195764183:ios:805c7236d9bb663d381792',
    messagingSenderId: '263195764183',
    projectId: 'first-app-ec476',
    storageBucket: 'first-app-ec476.firebasestorage.app',
    iosBundleId: 'com.example.pilem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDHDaPUsESddduduWjg3Pm9XEx4TBQzNk',
    appId: '1:263195764183:web:43216b982aa05dc3381792',
    messagingSenderId: '263195764183',
    projectId: 'first-app-ec476',
    authDomain: 'first-app-ec476.firebaseapp.com',
    storageBucket: 'first-app-ec476.firebasestorage.app',
    measurementId: 'G-NZ7LBSPRZ0',
  );
}
